markdown: rdiscount
permalink: /:title/
url: http://mrchanning.github.io/
name: MrChanning
author: MrChanning
qq: 404738958
email: qyn@w.cn
duoshuo: mrchanning
beian: 浙ICP备12026616号
cnzz: 119959
weibo: 1885061391
github: mrchanning
pygments: true
safe: true
paginate: 20
about: "MrChanning's blog"
